#######
### Configuration file for a training job that teaches Mistral 7B v0.1 to memorize a small batch from the SQLQA dataset
#######

###
# Model Configuration: Mistral 7B
###
base_model: mistralai/Mistral-7B-v0.1

# base model weight quantization
load_in_8bit: false
load_in_4bit: false
strict: false

# attention implementation
flash_attention: true

# finetuned adapter config
adapter: lora
lora_model_dir:
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_linear: true
lora_modules_to_save: # required when adding new tokens to LLaMA/Mistral
  - embed_tokens
  - lm_head
# for details, see https://github.com/huggingface/peft/issues/334#issuecomment-1561727994

###
# Dataset Configuration: sqlqa
###

datasets:
  # This will be the path used for the data when it is saved to the Volume in the cloud.
  - path: data.jsonl
    ds_type: json
    type:
      # JSONL file contains question, context, answer fields per line.
      # This gets mapped to instruction, input, output axolotl tags.
      field_instruction: question
      field_input: context
      field_output: answer
      # Format is used by axolotl to generate the prompt.
      format: |-
        [INST] Act as a creative script writer assistant by using the context and instructions below 
        {input}
        {instruction} [/INST]

# dataset formatting config
tokens: # add new control tokens from the dataset to the model
  - "[INST]"
  - " [/INST]"

special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

train_on_inputs: false

val_set_size: 0.05

# dataset packing config
sequence_len: 4096
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false
group_by_length: false

###
# Training Configuration: AdamW, CosineLR, deepspeed, many epochs
###

# random seed for better reproducibility
seed: 117

# optimizer config
optimizer: adamw_torch
learning_rate: 0.0001
lr_scheduler: cosine
warmup_steps: 10
gradient_accumulation_steps: 1
micro_batch_size: 16
weight_decay: 0.0

# axolotl saving config
dataset_prepared_path: last_run_prepared
output_dir: ./lora-out

# logging and eval config
logging_steps: 10
eval_steps: 10
save_strategy: "no"
num_epochs: 50

# wandb logging config
wandb_project: ai-scriptwriter

# training performance optimization config
bf16: auto
fp16: false
tf32: false
deepspeed: /workspace/axolotl/deepspeed_configs/zero3_bf16.json
gradient_checkpointing: true

###
# Miscellaneous Configuration
###

# prevents over-writing the config from the CLI
strict: false

# run with debug-level logs
debug:

# "Don't mess with this, it's here for accelerate and torchrun" -- axolotl docs
local_rank:
